### ISSUE TITLE
Feed/Include wiki roadmap into "pages" roadmap

### ISSUE THREAD

**Issue by nickarrow** [CMSgov/CMCS-DSG-DSS-Certification-Staging#53]
## What is the goal or purpose of this issue?
The purpose of this issue is the revise https://github.com/CMSgov/CMCS-DSG-DSS-Certification/blob/main/repo-roadmap.md so that that page is fed by our Wiki roadmap page: https://github.com/CMSgov/CMCS-DSG-DSS-Certification/wiki/MES-Certification-Repo-Roadmap.md

I tried doing this with a include_relative and couldn't figure it out, so I am hoping there is just a script or pointer type thing that we can use so that wiki page is continually fed into the "Pages" page. 

## This issue is resolved when...
- [ ] https://github.com/CMSgov/CMCS-DSG-DSS-Certification/blob/main/repo-roadmap.md is revised so that it is automatically fed by the related wiki roadmap page.

## Additional context
_Add any other context, screenshots, or links about the request here_

**Comment by nickarrow** [comment]
@mgwalker is this a thing you have bandwidth to help on by chance? I messed around and couldn't figure it out.

**Comment by mgwalker** [comment]
It is not easily possible. Jekyll/GitHub Pages doesn't support it natively, so we'd have to write some code to go fetch the content at build time. I'm not sure offhand if it's possible to customize the Jekyll build process in such a way that it would still run on GitHub Pages. GitHub takes a pretty strict approach, so it would have to be a process customization that Jekyll supports natively – you can't create your own arbitrary build process.

*If* that works, there's no way to do it "continuously." The `repo-roadmap` page could only be updated from the wiki whenever the site was rebuilt (so, after a pull request is merged, for example). It is ***possible*** to trigger a page build whenever someone edits the wiki, but it requires setting up some CI/CD processes. The easiest way would be with GitHub Actions but I *think* it could also be done with CircleCI (not 100% sure because I'm not sure the necessary `golem` event is published externally from GitHub, or if it's a purely internal event).

The only alternative I can think of would be to fetch the wiki content on the client-side and use a client-side Markdown processor to render it. That approach isn't too hard, but it changes your site from static to dynamic, and that changes the nature of any ATO-related questions. 😬

**Comment by nickarrow** [comment]
gotcha. Let's not pursue the auto-feed thing. Is there just an easy way to change the sidenavbar link to point directly to our wiki? I tried to do this via this pull, but something is wrong. Do you know if I goofed up the syntax? https://github.com/CMSgov/CMCS-DSG-DSS-Certification/pull/55/files

**Comment by mgwalker** [comment]
We should be able to do that, yes! I'll need to look at the sidenav code because it assumes all of the links are relative to the site, but it shouldn't be hard to allow external links. Would it be okay if I pushed to the branch for #55?

**Comment by nickarrow** [comment]
@mgwalker yeah of course. push away. We only need CMS review/approval when merging to main. So feel free to commit directly to the #55 branch
