### ISSUE TITLE
Conduct Post-MVP User Testing

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Certification-Staging#76]
## What is the goal or purpose of this issue?
Identify improvements that can be made to the site post-MVP

## This issue is resolved when...
- [x] Research has been conducted
- [x] Takeaways have been shorted into short term + long term actions 

## Additional context
_Add any other context, screenshots, or links about the request here_

**Comment by nickarrow** [comment]
Roadmap updated with key items.
- Would like to get more state-specific outcomes populated
- It would be good to make clear how the outcomes apply to new systems, major enhancements, or all systems. Make clear how outcomes apply to legacy systems (pre SMC certified systems).
- Identifying points of contact for specific follow-up outcomes would be nice.
- Explaining how a state might use the outcomes would be a good thing, is permission needed?
- Would prefer to have EVV included on the repo instead of content split between Repo and Medicaid.gov
- Would like the all of the key SMC content and appendix information posted to the repo as well, one-stop-shop.
- Would like to have the cert process included on this site.
- CMS-Required outcomes are not easy to align to Medicaid business as currently written.
- Need an explanation on "metrics reporting" - we don't want reporting for the sake of reporting. 
- Interest in an opportunity to suggest things in a collective way would be useful. 
- Would like an "opt-in" way to receive notifications/updates.
- Push notifications would be great.
- Email notifications are preferred.
- A CMS moderated discussions space is of interest to raise questions and get answers.
- An unmoderated discussion space may not be worth while, has been tried before.
- GitHub Roadmap link is in a strange place, needs more natural navigation. 
- CSV download error.
- Overview of which projects require certification versus those which just need to provide outcomes/metrics would be great.
